AWSTemplateFormatVersion: 2010-09-09

Description: Creates a DynamoDB table with Global Secondary Index (GSI) and Local Secondary Index (LSI) configured

Parameters:

  Owner:
    Type: String
    Default: tg

Resources:

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Customer
      AttributeDefinitions:
        - AttributeName: CustomerNumber
          AttributeType: S
        - AttributeName: CustomerType
          AttributeType: S
        - AttributeName: CustomerLocation
          AttributeType: S
      KeySchema:
        - AttributeName: CustomerNumber
          KeyType: HASH
        - AttributeName: CustomerType
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: CustomerLSI1
          KeySchema:
            - AttributeName: CustomerNumber
              KeyType: HASH
            - AttributeName: CustomerLocation
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      GlobalSecondaryIndexes:
        - IndexName: CustomerGSI1
          KeySchema:
            - AttributeName: CustomerType
              KeyType: HASH
            - AttributeName: CustomerLocation
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 0
            WriteCapacityUnits: 0
      Tags:
        - Key: Owner
          Value: !Ref Owner
