AWSTemplateFormatVersion: 2010-09-09

Description: Creates an ElastiCache Redis cluster

Parameters:
  ClusterName:
    Type: String
    Default: CacheClusterRedisDefault

  SubnetId1:
    Type: String

  SubnetId2:
    Type: String

  VpcSecurityGroupId:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/elasticache/${ClusterName}
      RetentionInDays: 7

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub ${ClusterName} Subnet Group
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ClusterName} Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 11211
          ToPort: 11211
          SourceSecurityGroupId: !Ref VpcSecurityGroupId

  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: !Ref ClusterName
      Engine: redis
      CacheNodeType: cache.t2.micro
      AZMode: single-az
      PreferredAvailabilityZone: us-east-2a
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      CacheSubnetGroupName: !Ref SubnetGroup
      LogDeliveryConfigurations:
        - DestinationDetails:
            CloudWatchLogsDetails:
              LogGroup: !Sub /aws/elasticache/${ClusterName}
          DestinationType: cloudwatch-logs
          LogFormat: json
          LogType: engine-log
      Tags:
        - Key: Owner
          Value: !Ref Owner
