AWSTemplateFormatVersion: 2010-09-09

Description: Creates a S3 bucket with Ownership Controls configurations

Parameters:
  BucketName:
    Type: String
    Default: tg-bucket-123456

  ObjectOwnership:
    Type: String
    AllowedValues:
      - BucketOwnerEnforced
      - ObjectWriter
      - BucketOwnerPreferred
    Default: BucketOwnerEnforced

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: !Ref ObjectOwnership
      Tags:
        - Key: Owner
          Value: !Ref Owner
