AWSTemplateFormatVersion: 2010-09-09

Description: Creates a S3 bucket encrypted

Parameters:
  BucketName:
    Type: String
    Default: tg-bucket-123456

  KMSMasterKeyID:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: false
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref KMSMasterKeyID
              SSEAlgorithm: aws:kms
      Tags:
        - Key: Owner
          Value: !Ref Owner
