AWSTemplateFormatVersion: 2010-09-09

Description: Creates a DynamoDB table

Parameters:

  ImportSourceSpecificationS3BucketSource:
    Type: String
    Default: tg-quicklabs-data

  Owner:
    Type: String
    Default: tg

Resources:

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Person
      AttributeDefinitions:
        - AttributeName: person_document_number
          AttributeType: S
        - AttributeName: person_birth_country
          AttributeType: S
      KeySchema:
        - AttributeName: person_document_number
          KeyType: HASH
        - AttributeName: person_birth_country
          KeyType: RANGE
      TableClass: STANDARD
      BillingMode: PAY_PER_REQUEST
      ImportSourceSpecification:
        InputFormat: CSV
        S3BucketSource: 
            S3Bucket: !Ref ImportSourceSpecificationS3BucketSource
      Tags:
        - Key: Owner
          Value: !Ref Owner