AWSTemplateFormatVersion: 2010-09-09

Description: Creates a DynamoDB table with auto Scaling configured

Parameters:

  Owner:
    Type: String
    Default: tg

Resources:

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Customer
      AttributeDefinitions:
        - AttributeName: CustomerId
          AttributeType: S
        - AttributeName: CustomerLocation
          AttributeType: S
      KeySchema:
        - AttributeName: CustomerId
          KeyType: HASH
        - AttributeName: CustomerLocation
          KeyType: RANGE
      TableClass: STANDARD
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        - Key: Owner
          Value: !Ref Owner

  ScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CustomerScalingRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateTable
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:SetAlarmState
                  - cloudwatch:DeleteAlarms
                Resource: "*"

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub table/Customer
      ScalableDimension: dynamodb:table:ReadCapacityUnits 
      # ScalableDimension: dynamodb:table:WriteCapacityUnits
      # ScalableDimension: dynamodb:index:ReadCapacityUnits 
      MaxCapacity: 4
      MinCapacity: 2      
      RoleARN: !GetAtt ScalingRole.Arn
      # ScheduledActions:
      #   ScheduledActionName: ScheduledAction
      #   Schedule: rate(1 minute)
      #   Schedule: at(2022-11-20T10:00:00)
      #   StartTime: 2022-11-20T10:00:00
      #   EndTime: 2022-11-20T10:05:00
      #   Timezone: String 
      #   ScalableTargetAction: 
      #     MaxCapacity: 8
      #     MinCapacity: 4       

  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CustomerReadAutoScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 75.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        DisableScaleIn: false
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
          # PredefinedMetricType: DynamoDBWriteCapacityUtilization  
          
     
  
