AWSTemplateFormatVersion: 2010-09-09

Description: Creates a S3 bucket with Lifecycle configuration

Parameters:
  BucketName:
    Type: String
    Default: tg-bucket-123456

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicReadWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: glacier
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 1
                StorageClass: GLACIER
            # ExpirationDate:
            # ObjectSizeGreaterThan:
            # AbortIncompleteMultipartUpload:
            # TagFilters
            Status: Enabled
      Tags:
        - Key: Owner
          Value: !Ref Owner
