AWSTemplateFormatVersion: 2010-09-09

Description: Creates a SNS Topic with deduplication enabled

Parameters:
  TopicName:
    Type: String
    Default: Topic

  Owner:
    Type: String
    Default: tg

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      ContentBasedDeduplication: true
      Tags:
        - Key: Owner
          Value: !Ref Owner
