AWSTemplateFormatVersion: 2010-09-09

Description: Creates a S3 bucket policy

Parameters:
  BucketName:
    Type: String
    Default: tg-bucket-123456

  AccountPrincipal:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${BucketName}/*
            Principal:
              AWS:
                - !Ref AccountPrincipal
            Condition:
              StringLike:
                "s3:x-amz-acl":
                  - "public-read"
