AWSTemplateFormatVersion: 2010-09-09

Description: Creates a SQS Queue policy

Parameters:
  QueueName:
    Type: String
    Default: Queue

  AccountPrincipal:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Sub https://sqs:${AWS::Region}.amazonaws.com/${AWS::AccountId}/${QueueName}
      PolicyDocument:
        Statement:
          - Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
            Effect: Allow
            Resource: arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueName}
            Principal:
              AWS:
                - !Ref AccountPrincipal
