AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Log Group for an ECS App

Parameters:
  EcsAppName:
    Type: String
    Default: CloudWatchLogsEcsApp

  # KmsKeyId:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/ecs/${EcsAppName}
      # KmsKeyId: !Ref KmsKeyId
      RetentionInDays: 7
      Tags:
        - Key: Owner
          Value: !Ref Owner

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EcsAppName}ExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub $EcsAppName}LogsPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "*"
