AWSTemplateFormatVersion: 2010-09-09

Description: Creates a DynamoDB Table

Parameters:

  Owner:
    Type: String
    Default: tg

Resources:

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: game
      AttributeDefinitions:
        - AttributeName: game_id
          AttributeType: S
        - AttributeName: game_platform_name
          AttributeType: S
      KeySchema:
        - AttributeName: game_id
          KeyType: HASH
        - AttributeName: game_platform_name
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
      Tags:
        - Key: Owner
          Value: !Ref Owner