AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Alarms for a RDS instance

Parameters:
  DBInstanceIdentifier:
    Type: String

  # AlarmEmail:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  # Topic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub ${DBInstanceIdentifier}Topic
  #     Subscription:
  #       - Endpoint: !Ref AlarmEmail
  #         Protocol: email
  #     Tags:
  #       - Key: Owner
  #         Value: !Ref Owner

  CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub CPUUtilization${DBInstanceIdentifier}
      AlarmDescription: !Sub CPUUtilization${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  FreeableMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub FreeableMemory${DBInstanceIdentifier}
      AlarmDescription: !Sub FreeableMemory${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: FreeableMemory
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ReadLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ReadLatency${DBInstanceIdentifier}
      AlarmDescription: !Sub ReadLatency${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: ReadLatency
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  WriteLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub WriteLatency${DBInstanceIdentifier}
      AlarmDescription: !Sub WriteLatency${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: WriteLatency
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  DatabaseConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub DatabaseConnections${DBInstanceIdentifier}
      AlarmDescription: !Sub DatabaseConnections${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: DatabaseConnections
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  DiskQueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub DiskQueueDepth${DBInstanceIdentifier}
      AlarmDescription: !Sub DiskQueueDepth${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: DiskQueueDepth
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  SwapUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub SwapUsage${DBInstanceIdentifier}
      AlarmDescription: !Sub SwapUsage${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: SwapUsage
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1000000000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  FreeLocalStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub FreeLocalStorage${DBInstanceIdentifier}
      AlarmDescription: !Sub FreeLocalStorage${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: FreeLocalStorage
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 100000000000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ReadIOPSAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ReadIOPS${DBInstanceIdentifier}
      AlarmDescription: !Sub ReadIOPS${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: ReadIOPS
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  BurstBalanceAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub BurstBalance${DBInstanceIdentifier}
      AlarmDescription: !Sub BurstBalance${DBInstanceIdentifier}
      Namespace: AWS/RDS
      MetricName: BurstBalance
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DBInstanceIdentifier
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions
