AWSTemplateFormatVersion: 2010-09-09

Description: Creates a Lambda function with DLQ config

Parameters:
  QueueName:
    Type: String
    Default: LambdaDLQ

  FunctionName:
    Type: String
    Default: LambdaDLQ

  BucketLambdaSourceCode:
    Type: String
    Default: tg-quicklabs-lambdasrc

  BucketKeyLambdaSourceCode:
    Type: String
    Default: LambdaDLQ.zip

  Owner:
    Type: String
    Default: tg

Resources:
  DLQName:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      DelaySeconds: 0
      MessageRetentionPeriod: 300
      Tags:
        - Key: Owner
          Value: !Ref Owner

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${FunctionName}ExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${FunctionName}ExecutionRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - sqs:SendMessage
                Resource: "*"

  Lambda:
    Type: AWS::Lambda::Function
    DependsOn: ExecutionRole
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: nodejs14.x
      Role: !GetAtt ExecutionRole.Arn
      Handler: index.handler
      Code:
        S3Bucket: !Ref BucketLambdaSourceCode
        S3Key: !Ref BucketKeyLambdaSourceCode
      DeadLetterConfig:
        TargetArn: !GetAtt DLQName.Arn
      Tags:
        - Key: Owner
          Value: !Ref Owner

  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    DependsOn: Lambda
    Properties:
      DestinationConfig:
        OnFailure:
          Destination: !GetAtt DLQName.Arn
      FunctionName: !Ref Lambda
      MaximumEventAgeInSeconds: 60
      MaximumRetryAttempts: 2
      Qualifier: $LATEST
