AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudFront distribution in front of a S3 Static Website

Parameters:
  LoggingBucketName:
    Type: String
    Default: tg-staticwebsite-logging-123456

  StaticWebsiteBucketName:
    Type: String
    Default: tg-staticwebsite-123456

  OriginAccessControlId:
    Type: String

  AcmCertificateArn:
    Type: String

  DomainName:
    Type: String

  HostedZoneId:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LoggingBucketName
      AccessControl: LogDeliveryWrite
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StaticWebsiteBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Owner
          Value: !Ref Owner

  StaticWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: StaticWebsiteBucket
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudFront
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${StaticWebsiteBucketName}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${OriginAccessControlId}

  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: [StaticWebsiteBucketPolicy]
    Properties:
      DistributionConfig:
        Comment: !Sub ${StaticWebsiteBucketName}Distribution
        DefaultRootObject: index.html
        Origins:
          - Id: !Sub ${StaticWebsiteBucketName}Origin
            DomainName: !Sub ${StaticWebsiteBucketName}.s3.${AWS::Region}.amazonaws.com
            # OriginPath: String
            OriginAccessControlId: !Ref OriginAccessControlId
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              OriginKeepaliveTimeout: 5
              OriginReadTimeout: 30
        DefaultCacheBehavior:
          TargetOriginId: !Sub ${StaticWebsiteBucketName}Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Logging:
          Bucket: !Sub ${LoggingBucketName}.s3.amazonaws.com
          Prefix: logs
        HttpVersion: http2
        Enabled: true
      Tags:
        - Key: Owner
          Value: !Ref Owner

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref HostedZoneId
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        #This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: true
