AWSTemplateFormatVersion: 2010-09-09

Description: Creates a S3 bucket with Intelligent Tiering configuration

Parameters:
  BucketName:
    Type: String
    Default: tg-bucket-123456

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      IntelligentTieringConfigurations:
        - Id:
          Prefix: log*
          # TagFilters:
          # - Name:
          # Value:
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 2
          Status: Enabled
      Tags:
        - Key: Owner
          Value: !Ref Owner
