AWSTemplateFormatVersion: 2010-09-09

Description: Creates a SQS Queue with Deduplication enabled

Parameters:
  QueueName:
    Type: String
    Default: QueueDeduplication

  Owner:
    Type: String
    Default: tg

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      ContentBasedDeduplication: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId
      Tags:
        - Key: Owner
          Value: !Ref Owner
