AWSTemplateFormatVersion: 2010-09-09

Description: Creates a SNS Topic with a Lambda function subscription

Parameters:
  TopicName:
    Type: String
    Default: SNSSubscriptionLambda

  FunctionName:
    Type: String
    Default: SNSSubscriptionLambda

  Owner:
    Type: String
    Default: tg

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${FunctionName}ExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${FunctionName}LogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "*"

  Lambda:
    Type: AWS::Lambda::Function
    DependsOn: ExecutionRole
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: nodejs14.x
      Role: !GetAtt ExecutionRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event, context) => {
            console.log('event', JSON.stringify(event));
            console.log('context', JSON.stringify('context'));
            context.succeed("Hello, I'm a SNS topic subscriber!");
          };
      Tags:
        - Key: Owner
          Value: !Ref Owner

  LambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: Lambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: sns.amazonaws.com

  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      # KmsMasterKeyId: !Ref KmsMasterKeyId
      Subscription:
        - Endpoint: !GetAtt Lambda.Arn
          Protocol: lambda
      Tags:
        - Key: Owner
          Value: !Ref Owner
