AWSTemplateFormatVersion: 2010-09-09

Description: Creates an IAM User Group

Parameters:
  GroupName:
    Type: String
    Default: ReadOnlyAccessGroup

  ManagedPolicyArns:
    Type: CommaDelimitedList
    Default: arn:aws:iam::aws:policy/ReadOnlyAccess

  Owner:
    Type: String
    Default: tg

Resources:
  UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref GroupName
      ManagedPolicyArns: !Ref ManagedPolicyArns
      Path: /
