AWSTemplateFormatVersion: 2010-09-09

Description: Creates an IAM Role

Parameters:
  RoleName:
    Type: String
    Default: CodeDeployService

  Owner:
    Type: String
    Default: tg

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RoleName}Role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      Policies:
        - PolicyName: !Sub ${RoleName}Policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::*
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
      Tags:
        - Key: Owner
          Value: !Ref Owner
