AWSTemplateFormatVersion: 2010-09-09

Description: Creates a DynamoDB table

Parameters:

  TableClass:
    Type: String
    Default: STANDARD
    AllowedValues:
      - STANDARD
      - STANDARD_INFREQUENT_ACCESS

  BillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    AllowedValues:
      - PAY_PER_REQUEST
      - PROVISIONED
  
  ReadCapacityUnits:
    Type: Number
    Default: 0

  WriteCapacityUnits:
    Type: Number
    Default: 0

  Owner:
    Type: String
    Default: tg

Resources:

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Person
      AttributeDefinitions:
        - AttributeName: person_document_number
          AttributeType: S
        - AttributeName: person_birth_country
          AttributeType: S
      KeySchema:
        - AttributeName: person_document_number
          KeyType: HASH
        - AttributeName: person_birth_country
          KeyType: RANGE
      TableClass: !Ref TableClass
      BillingMode: !Ref BillingMode
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      # SSESpecification:
      #   KMSMasterKeyId: !Ref KMSMasterKeyId
      #   SSEEnabled: false
      #   SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TimeToLiveSpecification:
        AttributeName: person_create_date
        Enabled: true
      Tags:
        - Key: Owner
          Value: !Ref Owner
