AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudFront distribution

Parameters:

  ApiName:
    Type: String
    Default: gameapi

  Owner:
    Type: String
    Default: tg

Resources:

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub ${ApiName}Distribution
        Origins:
          - Id: !Sub ${ApiName}Origin
            DomainName: !Sub ${RestApi}.execute-api.${AWS::Region}.amazonaws.com
        DefaultCacheBehavior:
          TargetOriginId: !Sub ${ApiName}Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          ViewerProtocolPolicy: allow-all
        Enabled: true
      Tags:
        - Key: Owner
          Value: !Ref Owner

Outputs:

  DomainName:
    Value: !GetAtt Distribution.DomainName
