AWSTemplateFormatVersion: 2010-09-09

Description: Creates a VPC Link

Parameters:

  VpcLinkName:
    Type: String
    Default: VpcLinkDefault

  SubnetId1:
    Type: String

  SubnetId2:
    Type: String

  SecurityGroupId:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:

  VpcLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: !Ref VpcLinkName
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2

Outputs:
  VpcLinkId:
    Value: !Ref VpcLink