AWSTemplateFormatVersion: 2010-09-09

Description: Creates a public bucket

Parameters:
  BucketName:
    Type: String
    Default: tg-public-bucket-123456

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicReadWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
      Tags:
        - Key: Owner
          Value: !Ref Owner
