AWSTemplateFormatVersion: 2010-09-09

Description: Creates an auto Scaling for a DynamoDB Global Secondary Index

Parameters:
  DynamDBTableName:
    Type: String

  ScalingRoleArn:
    Type: String

  MaxCapacity:
    Type: Number
    Default: 4

  MinCapacity:
    Type: Number
    Default: 2

  TargetValue:
    Type: Number
    Default: 70

  ScaleInCooldown:
    Type: Number
    Default: 60

  ScaleOutCooldown:
    Type: Number
    Default: 60

  Owner:
    Type: String
    Default: tg

Resources:
  # ScalingRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: !Sub ${DynamDBTableName}ScalingRole
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - application-autoscaling.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
  #     Path: "/"
  #     Policies:
  #       - PolicyName: !Sub ${DynamDBTableName}Policy
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - cloudwatch:PutMetricAlarm
  #                 - cloudwatch:DescribeAlarms
  #                 - cloudwatch:GetMetricStatistics
  #                 - cloudwatch:SetAlarmState
  #                 - cloudwatch:DeleteAlarms
  #                 - dynamodb:DescribeTable
  #                 - dynamodb:UpdateTable

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: dynamodb
      ResourceId: !Sub table/${DynamDBTableName}
      ScalableDimension: dynamodb:index:ReadCapacityUnits
      # ScalableDimension: dynamodb:index:WriteCapacityUnits
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      # If you run create-service-linked-role
      RoleARN: !Ref ScalingRoleArn
      # RoleARN: !GetAtt ScalingRole.Arn
      # ScheduledActions: List of ScheduledAction

  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${DynamDBTableName}ScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetValue
        ScaleInCooldown: !Ref ScaleInCooldown
        ScaleOutCooldown: !Ref ScaleOutCooldown
        DisableScaleIn: false
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
          # PredefinedMetricType: DynamoDBWriteCapacityUtilization
