AWSTemplateFormatVersion: 2010-09-09

Description: Creates a SQS Queue

Parameters:

  QueueName:
    Type: String
    Default: SampleQueue

  Owner:
    Type: String
    Default: tg

Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      DelaySeconds: 0
      MessageRetentionPeriod: 300
      Tags:
        - Key: Owner
          Value: !Ref Owner