AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Alarms for a CloudFront distribution

Parameters:
  DistributionId:
    Type: String

  # AlarmEmail:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  # Topic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub ${DistributionId}Topic
  #     Subscription:
  #       - Endpoint: !Ref AlarmEmail
  #         Protocol: email
  #     Tags:
  #       - Key: Owner
  #         Value: !Ref Owner

 RequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub Requests${DistributionId}
      AlarmDescription: !Sub Requests${DistributionId}
      Namespace: AWS/CloudFront
      MetricName: Requests
      Dimensions:
        - Name: DistributionId
          Value: !Ref DistributionId
      Statistic: Count
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions