AWSTemplateFormatVersion: 2010-09-09

Description: Creates a RDS DB Instance using MySQL engine

Parameters:
  SubnetId1:
    Type: String

  SubnetId2:
    Type: String

  DBInstanceID:
    Type: String
    Default: dbinstance

  DBName:
    Type: String
    Default: awsquickstartdatabase

  DBInstanceClass:
    Type: String
    Default: db.t2.micro

  DBUsername:
    Type: String
    NoEcho: true
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    Default: root

  DBPassword:
    Type: String
    NoEcho: true
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    Default: root123456

  Owner:
    Type: String
    Default: tg

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub ${DBName}DBSubnetGroup
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2
      Tags:
        - Key: Owner
          Value: !Ref Owner

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${DBName}SecurityGroup
      GroupDescription: !Sub ${DBName}SecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      Engine: mysql
      EngineVersion: 8.0
      Port: 3306
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt SecurityGroup.GroupId
      StorageType: standard
      AllocatedStorage: 5
      Tags:
        - Key: Owner
          Value: !Ref Owner
