AWSTemplateFormatVersion: 2010-09-09

Description: Creates a bucket used as a static website

Parameters:
  StaticWebsiteBucketName:
    Type: String
    Default: tg-staticwebsite-123456

  Route53RecordName:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StaticWebsiteBucketName
      # AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Owner
          Value: !Ref Owner

  # Public access via website URL
  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref StaticWebsiteBucket
  #     PolicyDocument:
  #       Statement:
  #         - Sid: AllowPublic
  #           Effect: Allow
  #           Action:
  #             - s3:GetObject
  #           Resource: !Sub arn:aws:s3:::${StaticWebsiteBucketName}/*
  #           Principal: "*"

  # Public access via Route 53
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: AllowPublic
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${Route53RecordName}/*
            Principal:
              AWS: "*"
