AWSTemplateFormatVersion: 2010-09-09

Description: Creates a bucket used as a static website

Parameters:
  StaticWebsiteBucketName:
    Type: String
    Default: tg-staticwebsite-123456

  Route53RecordName:
    Type: String

  OriginAccessControlId:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  StaticWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref StaticWebsiteBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: Owner
          Value: !Ref Owner

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticWebsiteBucket
      PolicyDocument:
        Statement:
          # Public access via website URL
          - Sid: AllowPublic
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${StaticWebsiteBucketName}/*
          # Public access via Route 53
          - Sid: Route53Record
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${Route53RecordName}/*
          # Public access via CloudFront
          - Sid: AllowCloudFront
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${StaticWebsiteBucketName}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${OriginAccessControlId}
