AWSTemplateFormatVersion: 2010-09-09

Description: Creates a REST API Gateway deployed using OpenAPI

Parameters:
  BucketOpenAPI:
    Type: String
    Default: tg-quicklabs-openapi

  BucketKeyOpenAPI:
    Type: String
    Default: openapi.yaml

  Owner:
    Type: String
    Default: tg

Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      BodyS3Location:
        Bucket: !Ref BucketOpenAPI
        Key: !Ref BucketKeyOpenAPI