AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudFront distribution in front of a S3 Bucket

Parameters:
  BucketName:
    Type: String
    Default: tg-cloudfrontbucket-123456

  CloudFrontOriginAccessIdentity:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Owner
          Value: !Ref Owner

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: Bucket
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudFront
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${BucketName}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}

  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: [Bucket, BucketPolicy]
    Properties:
      DistributionConfig:
        Comment: !Sub ${BucketName}Distribution
        Origins:
          - Id: !Sub ${BucketName}Origin
            DomainName: !Sub ${BucketName}.s3.${AWS::Region}.amazonaws.com
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: !Sub ${BucketName}Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: allow-all
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - BR
        Enabled: true
      Tags:
        - Key: Owner
          Value: !Ref Owner
