version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Compiling...
  post_build:
    commands:
      - echo Build completed...
artifacts:
  files:
    - index.js
    - package.json
