AWSTemplateFormatVersion: 2010-09-09

Description: Creates a secret attaches to a RDS instance

Parameters:
  SecretId:
    Type: String

  RotationLambdaARN:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  RDSSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RDSSecret
      Description: RDSSecret
      SecretString: '{"username": "HardcodedSecret", "password": "secret"}'
      Tags:
        - Key: Owner
          Value: !Ref Owner

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref RDSSecret,
            ":SecretString:username}}",
          ],
        ]
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref RDSSecret,
            ":SecretString:password}}",
          ],
        ]
      BackupRetentionPeriod: 0
      DBInstanceIdentifier: rotation-instance

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref RDSSecret
      TargetId: !Ref RDSInstance
      TargetType: AWS::RDS::DBInstance