AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Alarms for a Network Load Balancer

Parameters:
  LoadBalancerName:
    Type: String

  AvailabilityZone:
    Type: String

  TargetGroup:
    Type: String

  # AlarmEmail:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  # Topic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub ${TableName}Topic
  #     Subscription:
  #       - Endpoint: !Ref AlarmEmail
  #         Protocol: email
  #     Tags:
  #       - Key: Owner
  #         Value: !Ref Owner

  ActiveFlowCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ActiveFlowCount${LoadBalancerName}
      AlarmDescription: !Sub ActiveFlowCount${LoadBalancerName}
      Namespace: AWS/NetworkELB
      MetricName: ActiveFlowCount
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerName
        - Name: AvailabilityZone
          Value: !Ref AvailabilityZone
        - Name: TargetGroup
          Value: !Ref TargetGroup
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  NewFlowCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub NewFlowCount${LoadBalancerName}
      AlarmDescription: !Sub NewFlowCount${LoadBalancerName}
      Namespace: AWS/NetworkELB
      MetricName: NewFlowCount
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerName
        - Name: AvailabilityZone
          Value: !Ref AvailabilityZone
        - Name: TargetGroup
          Value: !Ref TargetGroup
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ProcessedBytesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ProcessedBytes${LoadBalancerName}
      AlarmDescription: !Sub ProcessedBytes${LoadBalancerName}
      Namespace: AWS/NetworkELB
      MetricName: ProcessedBytes
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerName
        - Name: AvailabilityZone
          Value: !Ref AvailabilityZone
        - Name: TargetGroup
          Value: !Ref TargetGroup
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 500000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  UnHealthyHostCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub UnHealthyHostCount${TableName}
      AlarmDescription: !Sub UnHealthyHostCount${TableName}
      Namespace: AWS/NetworkELB
      MetricName: UnHealthyHostCount
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerName
        - Name: AvailabilityZone
          Value: !Ref AvailabilityZone
        - Name: TargetGroup
          Value: !Ref TargetGroup
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  TCP_ELB_Reset_CountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub TCP_ELB_Reset_Count${TableName}
      AlarmDescription: !Sub TCP_ELB_Reset_Count${TableName}
      Namespace: AWS/NetworkELB
      MetricName: TCP_ELB_Reset_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref LoadBalancerName
        - Name: AvailabilityZone
          Value: !Ref AvailabilityZone
        - Name: TargetGroup
          Value: !Ref TargetGroup
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions
