AWSTemplateFormatVersion: 2010-09-09

Description: Creates a Glue Crawler and provides a script to create a Glue Job

Parameters:
  PocName:
    Type: String
    Default: testglue

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub tg-quicklabs-${PocName}
      AccessControl: BucketOwnerFullControl

  CrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        ["arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"]
      Policies:
        - PolicyName: S3BucketAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Join
                  - ""
                  - - !GetAtt Bucket.Arn
                    - "*"

  Database:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub database${PocName}
        Description: Database for a Glue test

  Crawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub crawler${PocName}
      Role: !GetAtt CrawlerRole.Arn
      DatabaseName: !Ref Database
      Targets:
        S3Targets:
          - Path: !Ref Bucket
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
