AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Alarms for a SQS queue

Parameters:
  QueueName:
    Type: String
    Default: CloudWatchAlarmsQueue

  # AlarmEmail:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      DelaySeconds: 0
      MessageRetentionPeriod: 300
      Tags:
        - Key: Owner
          Value: !Ref Owner

  # AlarmTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     Subscription:
  #       - Endpoint:
  #           Ref: AlarmEmail
  #         Protocol: email
  #     Tags:
  #       - Key: Owner
  #         Value: !Ref Owner

  ApproximateNumberOfMessagesVisibleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ApproximateNumberOfMessagesVisible${QueueName}
      AlarmDescription: !Sub ApproximateNumberOfMessagesVisible${QueueName}
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !Ref Queue
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 400
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ApproximateAgeOfOldestMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ApproximateAgeOfOldestMessage${QueueName}
      AlarmDescription: !Sub ApproximateAgeOfOldestMessage${QueueName}
      Namespace: AWS/SQS
      MetricName: ApproximateAgeOfOldestMessage
      Dimensions:
        - Name: QueueName
          Value: !Ref Queue
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions
