AWSTemplateFormatVersion: 2010-09-09

Description: Creates a S3 bucket with Object Lock configurations

Parameters:
  BucketName:
    Type: String
    Default: tg-objectlockbucket-123456

  InventoryDestinationPrefix:
    Type: String

  InventoryConfigurationPrefix:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: true
        Rule:
          DefaultRetention:
            Mode: COMPLIANCE
            Days: 7
            # Years: Integer
      Tags:
        - Key: Owner
          Value: !Ref Owner
