AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Auto Scaling for an Aurora Cluster

Parameters:
  AuroraClusterName:
    Type: String

  ScalingRoleArn:
    Type: String

  MaxCapacity:
    Type: Number
    Default: 4

  MinCapacity:
    Type: Number
    Default: 2

  TargetValue:
    Type: Number
    Default: 70

  ScaleInCooldown:
    Type: Number
    Default: 60

  ScaleOutCooldown:
    Type: Number
    Default: 60

  Owner:
    Type: String
    Default: tg

Resources:
  # ScalingRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: !Sub ${AuroraClusterName}ScalingRole
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #               - application-autoscaling.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
  #     Path: "/"
  #     Policies:
  #       - PolicyName: !Sub ${AuroraClusterName}Policy
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action:
  #                 - rds:AddTagsToResource
  #                 - rds:CreateDBInstance
  #                 - rds:DeleteDBInstance
  #                 - rds:DescribeDBClusters
  #                 - rds:DescribeDBInstances
  #                 - rds:ModifyDBCluster
  #                 - cloudwatch:PutMetricAlarm
  #                 - cloudwatch:DescribeAlarms
  #                 - cloudwatch:DeleteAlarms
  #               Resource: "*"

  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: rds
      ResourceId: !Sub cluster:${AuroraClusterName}
      ScalableDimension: rds:cluster:ReadReplicaCount
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      # If you run create-service-linked-role
      RoleARN: !Ref ScalingRoleArn
      # RoleARN: !GetAtt ScalingRole.Arn
      # ScheduledActions: List of ScheduledAction

  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${AuroraClusterName}ScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetValue
        ScaleInCooldown: !Ref ScaleInCooldown
        ScaleOutCooldown: !Ref ScaleOutCooldown
        DisableScaleIn: false
        PredefinedMetricSpecification:
          PredefinedMetricType: RDSReaderAverageCPUUtilization
          # PredefinedMetricType: RDSReaderAverageDatabaseConnections
