AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Auto Scaling for an ElastiCache Node Groups and Replicas

Parameters:
  ClusterName:
    Type: String

  ScalingRoleArn:
    Type: String

  MaxCapacity:
    Type: Number
    Default: 4

  MinCapacity:
    Type: Number
    Default: 2

  TargetValue:
    Type: Number
    Default: 70

  ScaleInCooldown:
    Type: Number
    Default: 60

  ScaleOutCooldown:
    Type: Number
    Default: 60

  Owner:
    Type: String
    Default: tg

Resources:
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: elasticache
      ResourceId: !Sub replication-group/${ClusterName}
      ScalableDimension: elasticache:replication-group:NodeGroups
      # ScalableDimension: elasticache:replication-group:Replicas
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      RoleARN: !Ref ScalingRoleArn
      # ScheduledActions: List of ScheduledAction

  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ${ClusterName}ScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetValue
        ScaleInCooldown: !Ref ScaleInCooldown
        ScaleOutCooldown: !Ref ScaleOutCooldown
        DisableScaleIn: false
        PredefinedMetricSpecification:
          PredefinedMetricType: ElastiCacheDatabaseMemoryUsageCountedForEvictPercentage
          # PredefinedMetricType: ElastiCachePrimaryEngineCPUUtilization
          # PredefinedMetricType: ElastiCacheReplicaEngineCPUUtilization
