AWSTemplateFormatVersion: 2010-09-09

Description: Creates an Application Load Balancer with weight listener rules

Parameters:
  FunctionName:
    Type: String
    Default: LBWithWeightListenerRules

  VpcId:
    Type: String

  SubnetId1:
    Type: String

  SubnetId2:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${FunctionName}ExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${FunctionName}ExecutionRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: "*"

  Lambda1:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      FunctionName: !Sub ${FunctionName}1
      Runtime: nodejs14.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event, context) => {
            console.log('event', JSON.stringify(event));
            const response = {
              "isBase64Encoded": false,
              "statusCode": 200,
              "statusDescription": "200 OK",
              "headers": {
                  "Set-cookie": "cookies",
                  "Content-Type": "application/json"
              },
              "body": "Hello from Lambda 1"
            };
            return response;
          };
      Tags:
        - Key: Owner
          Value: !Ref Owner

  Lambda2:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      FunctionName: !Sub ${FunctionName}2
      Runtime: nodejs14.x
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          exports.handler = async (event, context) => {
            console.log('event', JSON.stringify(event));
            const response = {
              "isBase64Encoded": false,
              "statusCode": 200,
              "statusDescription": "200 OK",
              "headers": {
                  "Set-cookie": "cookies",
                  "Content-Type": "application/json"
              },
              "body": "Hello from Lambda 2"
            };
            return response;
          };
      Tags:
        - Key: Owner
          Value: !Ref Owner

  LambdaPermission1:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Lambda1.Arn
      Action: "lambda:InvokeFunction"
      Principal: elasticloadbalancing.amazonaws.com

  LambdaPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Lambda2.Arn
      Action: "lambda:InvokeFunction"
      Principal: elasticloadbalancing.amazonaws.com

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub SgLb${FunctionName}
      GroupDescription: !Sub SgLb${FunctionName}
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub Lb${FunctionName}
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt LoadBalancerSecurityGroup.GroupId
      Subnets:
        - !Ref SubnetId1
        - !Ref SubnetId2
      Tags:
        - Key: Owner
          Value: !Ref Owner

  LoadBalancerTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub LbTg${FunctionName}1
      TargetType: lambda
      Targets:
        - Id: !GetAtt Lambda1.Arn
      Tags:
        - Key: Owner
          Value: !Ref Owner

  LoadBalancerTargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub LbTg${FunctionName}2
      TargetType: lambda
      Targets:
        - Id: !GetAtt Lambda2.Arn
      Tags:
        - Key: Owner
          Value: !Ref Owner

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties: 
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref LoadBalancerTargetGroup1
                Weight: 1
              - TargetGroupArn: !Ref LoadBalancerTargetGroup2
                Weight: 1
      Conditions:
        - Field: http-request-method
          HttpRequestMethodConfig:
            Values:
              - GET
      ListenerArn: !Ref LoadBalancerListener
      Priority: 1

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LoadBalancerTargetGroup1