AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Alarms for an ElastiCache Redis Cluster

Parameters:
  ClusterName:
    Type: String

  # AlarmEmail:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  # Topic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub ${FunctionName}Topic
  #     Subscription:
  #       - Endpoint: !Ref AlarmEmail
  #         Protocol: email
  #     Tags:
  #       - Key: Owner
  #         Value: !Ref Owner

  CPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub CPUUtilization${FunctionName}
      AlarmDescription: !Sub CPUUtilization${FunctionName}
      Namespace: AWS/ElastiCache
      MetricName: CPUUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref ClusterName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 50
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  SwapUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub SwapUsage${FunctionName}
      AlarmDescription: !Sub SwapUsage${FunctionName}
      Namespace: AWS/ElastiCache
      MetricName: SwapUsage
      Dimensions:
        - Name: ClusterName
          Value: !Ref ClusterName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 500000000
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  FreeableMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub FreeableMemory${FunctionName}
      AlarmDescription: !Sub FreeableMemory${FunctionName}
      Namespace: AWS/ElastiCache
      MetricName: FreeableMemory
      Dimensions:
        - Name: ClusterName
          Value: !Ref ClusterName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 500000000
      ComparisonOperator: LessThanOrEqualToThreshold
      TreatMissingData: missing 
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions