AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudFront distribution in front an API Gateway

Parameters:
  ApiName:
    Type: String
    Default: CloudFrontApiGateway

  StageName:
    Type: String
    Default: dev

  CloudFrontOriginAccessIdentity:
    Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref ApiName
      Description: !Ref ApiName
      DisableExecuteApiEndpoint: false
      Tags:
        - Key: Owner
          Value: !Ref Owner

  CustomerResource:
    Type: AWS::ApiGateway::Resource
    DependsOn: RestApi
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: customers

  MethodGetCustomers:
    Type: AWS::ApiGateway::Method
    DependsOn: RestApi
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref CustomerResource
      HttpMethod: GET
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{ "statusCode": 200 }'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '[ { "id": "1", "name": "CRISTIANO RONALDO" } ]'

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [MethodGetCustomers]
    Properties:
      RestApiId: !Ref RestApi

  Stage:
    Type: AWS::ApiGateway::Stage
    DependsOn: [Deployment]
    Properties:
      StageName: !Ref StageName
      Description: !Ref StageName
      RestApiId: !Ref RestApi
      DeploymentId: !Ref Deployment
      Tags:
        - Key: Owner
          Value: !Ref Owner

  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: [Stage]
    Properties:
      DistributionConfig:
        Comment: !Sub ${ApiName}Distribution
        Origins:
          - Id: !Sub ${ApiName}Origin
            DomainName: !Sub ${RestApi}.execute-api.${AWS::Region}.amazonaws.com
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              OriginKeepaliveTimeout: 5
              OriginReadTimeout: 30
        DefaultCacheBehavior:
          TargetOriginId: !Sub ${ApiName}Origin
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: allow-all
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - BR
        Enabled: true
      Tags:
        - Key: Owner
          Value: !Ref Owner

Outputs:
  ApiGatewayId:
    Value: !Ref RestApi

  DomainName:
    Value: !GetAtt Distribution.DomainName
