AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CodeDeploy Application using Lambda as the compute platform

Parameters:
  ApplicationName:
    Type: String
    Default: PocCodeDeploy

  Owner:
    Type: String
    Default: tg

Resources:
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref ApplicationName
      ComputePlatform: Lambda
      Tags:
        - Key: Owner
          Value: !Ref Owner

  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ApplicationName}CodeDeployServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      Policies:
        - PolicyName: !Sub ${ProjectName}CodeDeployServiceRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::* # It must be the bucket where the revisions will be uploaded
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref ApplicationName
      DeploymentConfigName: CodeDeployDefault.LambdaAllAtOnce
      DeploymentStyle:
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: BLUE_GREEN
      ServiceRoleArn: !GetAtt ServiceRole.Arn
      Tags:
        - Key: Owner
          Value: !Ref Owner
