AWSTemplateFormatVersion: 2010-09-09

Description: Creates an ElastiCache Memcached cluster

Parameters:
  ClusterName:
    Type: String
    Default: memcachedcluster

  SubnetId1:
    Type: String

  SubnetId2:
    Type: String

  SubnetId3:
    Type: String

  VpcSecurityGroupId:
    Type: String

  RedisPort:
    Type: Number
    Default: 6379

  AZMode:
    Type: String
    Default: cross-az
    AllowedValues:
      - single-az
      - cross-az

  NumCacheNodes:
    Type: Number
    Default: 3

  PreferredAvailabilityZone1:
    Type: String
    Default: us-east-2a

  PreferredAvailabilityZone2:
    Type: String
    Default: us-east-2b

  PreferredAvailabilityZone3:
    Type: String
    Default: us-east-2c

  Owner:
    Type: String
    Default: tg

Resources:
  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub ${ClusterName} Subnet Group
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2
        - !Ref SubnetId3

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ClusterName} Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref RedisPort
          ToPort: !Ref RedisPort
          SourceSecurityGroupId: !Ref VpcSecurityGroupId

  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      ClusterName: !Ref ClusterName
      CacheNodeType: cache.t2.micro
      Engine: memcached
      AZMode: !Ref AZMode
      PreferredAvailabilityZones:
        - !Ref PreferredAvailabilityZone1
        - !Ref PreferredAvailabilityZone2
        - !Ref PreferredAvailabilityZone3
      NumCacheNodes: !Ref NumCacheNodes
      Port: !Ref RedisPort
      VpcSecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      # CacheParameterGroupName: String
      CacheSubnetGroupName: !Ref SubnetGroup
      # NotificationTopicArn: String
      # SnapshotName: String
      # TransitEncryptionEnabled: true
      Tags:
        - Key: Owner
          Value: !Ref Owner
