package com.awsquickstarts.testdynamotableecsapp.model.entity;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@DynamoDBTable(tableName = "game")
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = { "id" })
@ToString
public class GameEntity {

    @Id
    @DynamoDBHashKey(attributeName = "game_id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "game_name")
    private String name;

    @DynamoDBAttribute(attributeName = "game_platform_name")
    private String platform;

    @DynamoDBAttribute(attributeName = "game_company_name")
    private String company;

    @DynamoDBAttribute(attributeName = "game_developer_name")
    private String developer;

}
