AWSTemplateFormatVersion: 2010-09-09

Description: Creates an ECS Cluster

Parameters:
  ClusterName:
    Type: String
    Default: FargateEcsCluster

  ContainerInsights:
    Type: String
    Default: disabled
    AllowedValues: ["enabled", "disabled"]

  Owner:
    Type: String
    Default: tg

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: !Ref ContainerInsights
      Tags:
        - Key: Owner
          Value: !Ref Owner