AWSTemplateFormatVersion: 2010-09-09

Description: Creates a CloudWatch Alarms for a DynamoDB table

Parameters:
  TableName:
    Type: String
    Default: CloudWatchAlarmsDynamoDB

  # AlarmEmail:
  #   Type: String

  Owner:
    Type: String
    Default: tg

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Person
      AttributeDefinitions:
        - AttributeName: table_pk
          AttributeType: S
        - AttributeName: table_sk
          AttributeType: S
      KeySchema:
        - AttributeName: table_pk
          KeyType: HASH
        - AttributeName: table_sk
          KeyType: RANGE
      TableClass: STANDARD
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        - Key: Owner
          Value: !Ref Owner

  # Topic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     TopicName: !Sub ${TableName}Topic
  #     Subscription:
  #       - Endpoint: !Ref AlarmEmail
  #         Protocol: email
  #     Tags:
  #       - Key: Owner
  #         Value: !Ref Owner

  ReadThrottleEventsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ReadThrottleEvents${TableName}
      AlarmDescription: !Sub ReadThrottleEvents${TableName}
      Namespace: AWS/DynamoDB
      MetricName: ReadThrottleEvents
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 4
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  WriteThrottleEventsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub WriteThrottleEvents${TableName}
      AlarmDescription: !Sub WriteThrottleEvents${TableName}
      Namespace: AWS/DynamoDB
      MetricName: WriteThrottleEvents
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 6
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  SuccessfulRequestLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub SuccessfulRequestLatency${TableName}
      AlarmDescription: !Sub SuccessfulRequestLatency${TableName}
      Namespace: AWS/DynamoDB
      MetricName: SuccessfulRequestLatency
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: LessThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  SystemErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub SystemErrors${TableName}
      AlarmDescription: !Sub SystemErrors${TableName}
      Namespace: AWS/DynamoDB
      MetricName: SystemErrors
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  UserErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub UserErrors${TableName}
      AlarmDescription: !Sub UserErrors${TableName}
      Namespace: AWS/DynamoDB
      MetricName: UserErrors
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ConsumedReadCapacityUnitsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ConsumedReadCapacityUnits${TableName}
      AlarmDescription: !Sub ConsumedReadCapacityUnits${TableName}
      Namespace: AWS/DynamoDB
      MetricName: ConsumedReadCapacityUnits
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ConsumedWriteCapacityUnitsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ConsumedWriteCapacityUnits${TableName}
      AlarmDescription: !Sub ConsumedWriteCapacityUnits${TableName}
      Namespace: AWS/DynamoDB
      MetricName: ConsumedWriteCapacityUnits
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 3
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions

  ReturnedItemCountAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ReturnedItemCount${TableName}
      AlarmDescription: !Sub ReturnedItemCount${TableName}
      Namespace: AWS/DynamoDB
      MetricName: ReturnedItemCount
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 50
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing
      # AlarmActions:
      #   - !GetAtt Topic.TopicArn
      # OKActions
      # InsufficientDataActions
