AWSTemplateFormatVersion: 2010-09-09

Description: Creates a Security Group to allow SSH conection;

Parameters:

  SecurityGroupName:
    Type: String
    Default: SSH

  VpcId:
    Type: String
  
  DefaultPortSSH:
    Type: String
    Default: 22
  
  IpIngress1:
    Type: String
  
  Owner:
    Type: String
    Default: tg

Resources:

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Sg${SecurityGroupName}
      GroupDescription: !Sub Sg${SecurityGroupName}
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref DefaultPortSSH
          ToPort: !Ref DefaultPortSSH
          CidrIp: !Ref IpIngress1
      Tags:
        - Key: Owner
          Value: !Ref Owner

Outputs:

  SgSSH:
    Value: !GetAtt SSHSecurityGroup.GroupId
    Export:
      Name: !Sub Sg${SecurityGroupName}GroupId